def get_model_paths(type):
    model_paths = {
        (4, 32): f'../ex/{type}/grid4_bin32/model/correlation_model.pth',
        (4, 64): f'../ex/{type}/grid4_bin64/model/correlation_model.pth',
        (4, 128): f'../ex/{type}/grid4_bin128/model/correlation_model.pth',
        (4, 256): f'../ex/{type}/grid4_bin256/model/correlation_model.pth',
        (5, 32): f'../ex/{type}/grid5_bin32/model/correlation_model.pth',
        (5, 64): f'../ex/{type}/grid5_bin64/model/correlation_model.pth',
        (5, 128): f'../ex/{type}/grid5_bin128/model/correlation_model.pth',
        (5, 256): f'../ex/{type}/grid5_bin256/model/correlation_model.pth',
        (6, 32): f'../ex/{type}/grid6_bin32/model/correlation_model.pth',
        (6, 64): f'../ex/{type}/grid6_bin64/model/correlation_model.pth',
        (6, 128): f'../ex/{type}/grid6_bin128/model/correlation_model.pth',
        (6, 256): f'../ex/{type}/grid6_bin256/model/correlation_model.pth',
        (7, 32): f'../ex/{type}/grid7_bin32/model/correlation_model.pth',
        (7, 64): f'../ex/{type}/grid7_bin64/model/correlation_model.pth',
        (7, 128): f'../ex/{type}/grid7_bin128/model/correlation_model.pth',
        (7, 256): f'../ex/{type}/grid7_bin256/model/correlation_model.pth',
        (8, 32): f'../ex/{type}/grid8_bin32/model/correlation_model.pth',
        (8, 64): f'../ex/{type}/grid8_bin64/model/correlation_model.pth',
        (8, 128): f'../ex/{type}/grid8_bin128/model/correlation_model.pth',
        (8, 256): f'../ex/{type}/grid8_bin256/model/correlation_model.pth',
        (9, 64): f'../ex/{type}/grid9_bin64/model/correlation_model.pth',
        (9, 128): f'../ex/{type}/grid9_bin128/model/correlation_model.pth',
        (9, 256): f'../ex/{type}/grid9_bin256/model/correlation_model.pth',
        (10, 64): f'../ex/{type}/grid10_bin64/model/correlation_model.pth',
        (10, 128): f'../ex/{type}/grid10_bin128/model/correlation_model.pth',
        (10, 256): f'../ex/{type}/grid10_bin256/model/correlation_model.pth',
    }
    return model_paths